version: "3.8"
services:
  app:
    environment:
      - DEBUG=1
    container_name: dates_fastapi
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from the .env file
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: dates_postgres
    user: "root"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
