[tool.black]
line-length = 88
include = '\.pyi?$'
skip_string_normalization = false
string_normalization = true
fast = true
use_tabs = false

[tool.flake8]
ignore = "E203, E266, E501, W503, F403, F401"
exclude = ".git, .mypy_cache, .pytest_cache, build, dist"
max-line-length = 88
max-complexity = 18
select = "B,C,E,F,W,T4,B9"

[tool.isort]
profile = 'black'

[tool.autoflake]
check = false
